dist: trusty
sudo: false
os:
- linux
addons:
  apt:
    packages:
    - python-yaml
env:
  matrix:
  - TEST_TARGET="hostnames-test"
  global:
  - secure: YryCFi/KnXiYuH3pgu6kLWqIG16ZrIwzx2KL/Ip3bOlZ9tBw+M4jfxFzS73aDSBI5ctH0zPCQpRsoYj/bSNqaojP4QJGfM9nTdJeVTmKKKQECCk6PViDyxDKVRA6yVjnYbDunkoj3+7govCHxeSH65JFQeop6VvwdHPBYJUW21s2DFyxER59faPlvuaU/1MtPpazBaXtDArt1AOsMp7ri7BYQC9KkVxCJefkBOYrDSCK99i0yiPqStwmdC7eMY3q2WUMmqJNbezcu82/THocyu5Qc4vzh2JXyROJ4qhOexBA6GbfpSR4C9NMtn4czNYdGA7gE/Gu6Yp5Ot2ulDU2LBmXN97yU5YQP1lf2ZRCz8wWU58XXGI7Yv2cqdGKafqeeb7sGVD7fxScebfPvbUubOy3qDvdX16fdiwnXEiJ3mG8LkgUc1k9/IMHT23qDq1ntsN2OA3/B+7H597OZ0XOPbU44HY5FK0v4mHDZT/9KIZLhPYV4G+eDl90aOfkw9lTtDqXIqRW0lEZnwlzjz/33WC4T+vP8NZbIdzumtJafdIhIWVDzcEdIivvHvzaGuGhohN58+1IvF+SF1zHXZPjwevxX84qVkh0NtksZr18Rdp68XiBbDV+lTPqtCF2jNJlg3Mj/6cl/yuP2AtFDgPrS65OY0tWLfLVgn/YbSAZy+w=
  - secure: QWv2E8FAIFPhm5B+ncFUSzAhS3lY2aIu1VG3CPYqiSd6fXZVASxKJ5lQ1zyHuptUSu4FE+DFRs1Dv+1fMFE0102SLdpiIxEh5rCgnYlZxvWCGYdXq3TGiO8qtVWYqyr2LCs4m0ztbhIVpv4mRW8apIOta6JSBWq0JndUXw4Sld1sYqzFUPkz4C7/PZc0iGIJa0/o2WS7tIh05ggrXpOOnQtcjduOH9D2Wtl7PfJJ0ssmcmxR/OD0tUgzje4ztu6zbkwFVZSmHvle8q8ut75tBdCjK+jfcmRTTl4HxoWWKSHJFh7MOSNuB/LtaXz7bf3m+DMxxfjNBKY5H0uHmB3k8AnGKvuyzgJpqqHoMKyENX6YTN3E03+MfoOUev893Mgp9AZlU5HH1LGCKAcogcNKJga6oWrDp6jTJrnk1WqRAVhaHj7KRQBtIqJrb3QMsYJ3XWqP1mPShmZDRNmoIQ/mcESHsHWM9e8GWKOpfUJ9j/6D6VerGBFylYbFJp7Q63JD7Z/jkA53S4Uj/ieq/sF3sMquMafx6rNj3k2z2MjV6mQ3otN55BAFCBMo6BxMSM5syD0AlMyMpjRN1TN+Dv07hU6abRSA2VDHAMDjwqx52dWNdZmwiC+sSBGIK9KPM9k5VNhMXGSUiHKfWUQ1kF+co0305xAAwZfl5qK0eO6ZPsQ=
  - secure: G6hzRe1Emn5aJZht/Fq1Cq0i9lZRUj3ZwPlap2Hx/r6fxpnBNOn30E9Bpxyno1/3iWgY+dzEq37JVqs2zOEL4+qL86gE7EDrrKwBnMNt8WcxzVt0mT4mIJ/J2Ju/kHBxIXZffhUa5JdrOvYRisvxJ+anq2v4idBeqD7C6TSQ1kYN7OWR/mxH0RXXnTRgf8Hfqv1mtrFnIVxXmS7nBhSAZN9H7yaxdicPaCT3mJuIQ784BVXyedd19oU5UytzBaUCFp8zKptrHtj5xeZJFClBDFDdN+AWvrTg03+omiF3AKQj89BEbSFXkyItV/uUqbZOxbgAcAty9xzv0uBxRwAOJq3QkOgJN7YY6am2DIG8kfjOj8zOCYLt6sk9u8TdX/GZg/XyMdvC4R5YWb48J91sdE3pDPar9UPSivTkLT61G+gBAIJXKa2tJJsLpH5BRSdTC0nO6Aebdt7utEDWxtgCpDiMVpcY8gYa4nusH5Pe++PkKkvo/15FEJky3m8+q2Kj7ByvUAh1W3kKpXaMnLE667dgyavt97DsbsgOjOMTHH7053wO/j7FfW23EK/HFlcV2DxWjZ/Q/hj7yeoeJRfepoT7YqpQZAZY/Og1j1PvIYNBzi10BEkcyFhUoZyyBGrJNKPWkcswjEp9/JVfgnNlptO/U2iXM3OX9PmlxQV3n80=

before_script:
- export PATH=$HOME/.local/bin:$PATH
- pip install --upgrade pip
- pip install --user chube boto jinja2 httplib2 six
- make init-tests

script:
- . d
- make $TEST_TARGET

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
