dist: trusty
sudo: false
os:
- linux
addons:
  apt:
    packages:
    - python-yaml
env:
  matrix:
  - TEST_TARGET="linode-test"
  - TEST_TARGET="ec2-test"
  global:
  - secure: p1tDwCvP4ZBiVMBf6npSv0a/HdK1NIFkgWwRyj6IIL8ueBOsC806x1E1V+SEU5q1LnQTDC/5+Ss4D+6eP3Cl2RW+MxWU9Vt4tERtiE4MKXjsEj76fLzmDfAAAQr2909NgiS/drzWKBbCnq664/z2vQTK4Vm1Y/F3Dxo67h8Vi6D87288yzxCFqOuDwdmrwnwLgL43TKO2ETlbQDP2CAYR6E3hbytlOPLqvS8VpcS986ejD1YFygc8BkWsW5922BDJJ6GENcI6V45MrVZcr4/3UyJ2lCoUSdJBsQ2CqM1PuXGSJk5H3RCJms6WjGQUD3YwPiut5Jwjelp94sAwrIJgXQniiDNUFv44YTOhOVyFH7EuPwll1dh+aUXZWyryApCq09B0aeUYHzzDP+T1wfSJcuvdNtapqq4EOCDlas3sOkbnCQbZIZ0xoDsnppZBXEWG7+BD0fnk51pBhsyQ9eWGtk0A7/jfOcbRufBA1LCgegHVk8z9gSBdb9EBJFUqUSFPMrK4v1RGu4YxZjAvDTGcixwFTUj/WW4L94FTpaT/oJyXX3zMWOP2BCdt8Dxm3bJ4J0/DQplK3u682Bq43begm+tjrOSozYoE0toGohE564xGR+W4aR14hc5KwIIWYZtpKsd7lWLwtKNXRtWQJI1i+w8KDWJwepQIcsQcaNCHBw=
  - secure: YryCFi/KnXiYuH3pgu6kLWqIG16ZrIwzx2KL/Ip3bOlZ9tBw+M4jfxFzS73aDSBI5ctH0zPCQpRsoYj/bSNqaojP4QJGfM9nTdJeVTmKKKQECCk6PViDyxDKVRA6yVjnYbDunkoj3+7govCHxeSH65JFQeop6VvwdHPBYJUW21s2DFyxER59faPlvuaU/1MtPpazBaXtDArt1AOsMp7ri7BYQC9KkVxCJefkBOYrDSCK99i0yiPqStwmdC7eMY3q2WUMmqJNbezcu82/THocyu5Qc4vzh2JXyROJ4qhOexBA6GbfpSR4C9NMtn4czNYdGA7gE/Gu6Yp5Ot2ulDU2LBmXN97yU5YQP1lf2ZRCz8wWU58XXGI7Yv2cqdGKafqeeb7sGVD7fxScebfPvbUubOy3qDvdX16fdiwnXEiJ3mG8LkgUc1k9/IMHT23qDq1ntsN2OA3/B+7H597OZ0XOPbU44HY5FK0v4mHDZT/9KIZLhPYV4G+eDl90aOfkw9lTtDqXIqRW0lEZnwlzjz/33WC4T+vP8NZbIdzumtJafdIhIWVDzcEdIivvHvzaGuGhohN58+1IvF+SF1zHXZPjwevxX84qVkh0NtksZr18Rdp68XiBbDV+lTPqtCF2jNJlg3Mj/6cl/yuP2AtFDgPrS65OY0tWLfLVgn/YbSAZy+w=
  - secure: QWv2E8FAIFPhm5B+ncFUSzAhS3lY2aIu1VG3CPYqiSd6fXZVASxKJ5lQ1zyHuptUSu4FE+DFRs1Dv+1fMFE0102SLdpiIxEh5rCgnYlZxvWCGYdXq3TGiO8qtVWYqyr2LCs4m0ztbhIVpv4mRW8apIOta6JSBWq0JndUXw4Sld1sYqzFUPkz4C7/PZc0iGIJa0/o2WS7tIh05ggrXpOOnQtcjduOH9D2Wtl7PfJJ0ssmcmxR/OD0tUgzje4ztu6zbkwFVZSmHvle8q8ut75tBdCjK+jfcmRTTl4HxoWWKSHJFh7MOSNuB/LtaXz7bf3m+DMxxfjNBKY5H0uHmB3k8AnGKvuyzgJpqqHoMKyENX6YTN3E03+MfoOUev893Mgp9AZlU5HH1LGCKAcogcNKJga6oWrDp6jTJrnk1WqRAVhaHj7KRQBtIqJrb3QMsYJ3XWqP1mPShmZDRNmoIQ/mcESHsHWM9e8GWKOpfUJ9j/6D6VerGBFylYbFJp7Q63JD7Z/jkA53S4Uj/ieq/sF3sMquMafx6rNj3k2z2MjV6mQ3otN55BAFCBMo6BxMSM5syD0AlMyMpjRN1TN+Dv07hU6abRSA2VDHAMDjwqx52dWNdZmwiC+sSBGIK9KPM9k5VNhMXGSUiHKfWUQ1kF+co0305xAAwZfl5qK0eO6ZPsQ=

before_script:
- export PATH=$HOME/.local/bin:$PATH
- pip install --upgrade pip
- pip install --user chube boto jinja2 httplib2 six
- make init-tests

script:
- . d
- make $TEST_TARGET

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
